all:
  
  cre8SagePay:
    VPSProtocol:       2.23
    Vendor:            MY_VENDOR_ID
    TxType:            PAYMENT
    
    encryption_key:    'KEY_RECEIVED_FROM_SAGE'
    url:               'https://test.sagepay.com/gateway/service/vspform-register.vsp'
    
    Currency:          GBP
    Description:       'XXXYYY Online Order'
    
    SuccessURL:        @paymentOk
    FailureURL:        @paymentFail
  
dev:
  
  cre8SagePay:
    url:               'https://test.sagepay.com/Simulator/VSPFormGateway.asp'
    encryption_key:    'LiRaZj8GHEZOxIeS'
  
prod:
  
  cre8SagePay:
    url:               'https://test.sagepay.com/Simulator/VSPFormGateway.asp'
    encryption_key:    'LiRaZj8GHEZOxIeS'
  
#  cre8SagePay:
#    url:               'https://test.sagepay.com/gateway/service/vspform-register.vsp'
#    encryption_key:    'tMHn66JCvLJak2yC'
#
#    url:               'https://test.sagepay.com/Simulator/VSPFormGateway.asp'
#    encryption_key:    'LiRaZj8GHEZOxIeS'
#
#    url:               'https://live.sagepay.com/gateway/service/vspform-register.vsp'
#    encryption_key:    'XXXXXXXXXXXXXXX'
